-- Generated from seed-recipes.json
-- Start a transaction
BEGIN;

-- Insert users and their profiles
DO $$ 
DECLARE
  user_id uuid;
  username text;
BEGIN

  -- Create admin user
  user_id := 'b02e2f4a-94ed-45ad-a745-435d986db886';
  INSERT INTO auth.users (
    id,
    instance_id,
    aud,
    role,
    email,
    encrypted_password,
    email_confirmed_at,
    invited_at, confirmation_token, confirmation_sent_at, recovery_token, recovery_sent_at, email_change_token_new, email_change, email_change_sent_at, last_sign_in_at,
    raw_app_meta_data,
    raw_user_meta_data,
    created_at,
    updated_at
  ) VALUES (
    user_id,
    '00000000-0000-0000-0000-000000000000',
    'authenticated',
    'authenticated',
    'admin@recipe.app',
    crypt('password123', gen_salt('bf')),
    now(),
    NULL, '', NULL, '', NULL, '', '', NULL, NULL,
    '{"provider":"email","providers":["email"]}'::jsonb,
    '{"name":"Admin"}'::jsonb,
    now(),
    now()
  );

  -- Insert admin profile
  INSERT INTO public.profiles (id, name, username, avatar_url)
  VALUES (user_id, 'Admin', 'admin', user_id || '.png');

  -- Insert sample recipes
  INSERT INTO public.recipes (
    id,
    name,
    original_name,
    original_language,
    description,
    category,
    subcategory,
    components,
    instructions,
    instruction_sections,
    preparation,
    total_time,
    servings,
    difficulty,
    created_by,
    status,
    image_url
  ) VALUES   (
    'd2d3c8a0-40a3-4a8e-8c6b-6f8e1a2b3c4d',
    'Chocolate Chip Cookies',
    NULL,
    NULL,
    'Classic chocolate chip cookies that are crispy on the outside and chewy on the inside',
    'sweets',
    'cookies',
    '[{"id":"main","name":"Main","description":"Primary cookie ingredients","order":1,"ingredients":[{"name":"Butter","amount":"100","unit":"g","is_flour":false},{"name":"Brown sugar","amount":"100","unit":"g","is_flour":false},{"name":"Sugar","amount":"100","unit":"g","is_flour":false},{"name":"Sea salt","amount":"2","unit":"g","is_flour":false},{"name":"Egg","amount":"40","unit":"g","is_flour":false},{"name":"Flour T55 Classique","amount":"81","unit":"g","is_flour":false},{"name":"Flour T45 Gruau","amount":"100","unit":"g","is_flour":false},{"name":"Baking soda","amount":"1","unit":"g","is_flour":false},{"name":"Baking powder","amount":"2","unit":"g","is_flour":false},{"name":"Dark chocolate chips","amount":"200","unit":"g","is_flour":false}]}]'::jsonb,
    '[{"step":"1","content":"Mix sugar, butter and salt till soft and fluffy on high speed. Add egg gradually at low speed, beating well after each addition. Add dry ingredients and beat until incorporated. Add chocolate chips and beat until well-incorporated. This should take about 5 minutes.","remark":"Butter should be at room temperature - cold butter won''t cream properly and melted butter won''t hold air. The cookie dough should be soft paste texture."},{"step":"2","content":"Place the cookie dough in chiller at 4°C for 1 - 2 hours.","remark":"Chilling helps create better taste and texture."},{"step":"3","content":"Take out from chiller, shape into balls of 30g each. Place on a baking sheet lined with parchment paper."},{"step":"4","content":"Apply egg wash to the cookies."},{"step":"5","content":"Bake at 170°C for 10 minutes."},{"step":"6","content":"Let cool for 10 minutes."}]'::jsonb,
    NULL,
    '["Preheat oven to 190°C"]'::jsonb,
    20,
    24,
    2,
    user_id,
    'published',
    'd2d3c8a0-40a3-4a8e-8c6b-6f8e1a2b3c4d-thumbnail.png'
  ),
  (
    'f0f1f2f3-f4f5-f6f7-f8f9-fafbfcfdfeff',
    'Classic French Baguette',
    NULL,
    NULL,
    'Classic white bread with a crispy crust and chewy interior',
    'breads',
    'lean-dough',
    '[{"id":"main","name":"Main","description":"Primary bread ingredients","order":1,"ingredients":[{"name":"T55 French Flour","amount":"840","unit":"g","is_flour":true},{"name":"Water","amount":"650","unit":"g","is_flour":false},{"name":"Salt","amount":"20","unit":"g","is_flour":false},{"name":"Fresh yeast","amount":"13","unit":"g","is_flour":false}]}]'::jsonb,
    '[{"step":"1","content":"Mix flour and water on Low speed for 5 minutes."},{"step":"2","content":"Add salt and yeast. Let rest for 10 minutes (autolyse)."},{"step":"3","content":"(PA mixing) Mix on Low speed for 5 minutes, and continue on High speed for 5 minutes.","remark":"PA (Pétrissage Amélioré - Improved Kneading) method provides moderate gluten development ideal for lean doughs like baguettes. The shorter high-speed phase prevents overheating while achieving proper dough structure."},{"step":"4","content":"Bulk ferment for 40 - 60 minutes at room temperature of 25°C."},{"step":"5","content":"Add a little flour on the bench to stop the dough from sticking. Divide the dough into pieces weighing 350g each."},{"step":"6","content":"Shape into rectangles. Fold the longer side of the dough inward like a letter and press gently to seal. This folded part should be two-thirds of the width of the baguette. Then, fold the bottom edge of the dough inward like a letter and press down gently to seal. Flatten well using the palm of your hand. Let rest for 5 minutes."},{"step":"7","content":"Gently roll the dough against the work surface to form a baguette shape."},{"step":"8","content":"Transfer to a floured couche or towel. Let rest for 40 - 60 minutes at room temperature of 25°C."},{"step":"9","content":"Preheat oven to 240°C."},{"step":"10","content":"At the end of proofing, score the dough at 30° angle with a lame or sharp knife, making marks parallel to each other."},{"step":"11","content":"Steam the oven. Bake in oven at 240°C for 20 minutes.","remark":"To create steam, place a pan of hot water on the bottom of the oven or spray the oven walls with water just before closing the door."},{"step":"12","content":"Let cool for 10 minutes."}]'::jsonb,
    NULL,
    '["Preheat oven to 240°C"]'::jsonb,
    30,
    2,
    3,
    user_id,
    'published',
    'f0f1f2f3-f4f5-f6f7-f8f9-fafbfcfdfeff-thumbnail.png'
  ),
  (
    '624cb94e-6168-4ed7-97df-46fc552ff002',
    'Bordeaux Crown',
    NULL,
    NULL,
    'A traditional, crown-shaped bread from Bordeaux, France',
    'breads',
    'lean-dough',
    '[{"id":"main","name":"Main","description":"Primary bread ingredients","order":1,"ingredients":[{"name":"T55 French Flour","amount":"730","unit":"g","is_flour":true},{"name":"Water","amount":"475","unit":"g","is_flour":false},{"name":"Salt","amount":"15","unit":"g","is_flour":false},{"name":"Fresh yeast","amount":"9","unit":"g","is_flour":false}]}]'::jsonb,
    '[{"step":"1","content":"Mix flour and water on Low speed for 5 minutes."},{"step":"2","content":"Add salt and yeast. Let rest for 10 minutes (autolyse)."},{"step":"3","content":"(PA mixing) Mix on Low speed for 5 minutes, and continue on High speed for 5 minutes.","remark":"PA (Pétrissage Amélioré - Improved Kneading) method provides moderate gluten development ideal for lean doughs like baguettes. The shorter high-speed phase prevents overheating while achieving proper dough structure."},{"step":"4","content":"Bulk ferment for 40 - 60 minutes at room temperature of 25°C."},{"step":"5","content":"Add a little flour on the bench to stop the dough from sticking. Divide the dough into pieces weighing 300g each. Round each piece into a ball."},{"step":"6","content":"Flour your finger and poke into the center of the ball. Pull the dough outwards until the hole becomes big enough. Place the dough on a floured couche or towel. Let rest for 40 - 60 minutes at room temperature of 25°C."},{"step":"7","content":"At the end of proofing, score the dough 1 round around the couronne dough with a lame or sharp knife."},{"step":"8","content":"Steam the oven. Bake in oven at 240°C for 24 minutes."},{"step":"9","content":"Let cool for 10 minutes."}]'::jsonb,
    NULL,
    '["Preheat oven to 240°C"]'::jsonb,
    150,
    4,
    2,
    user_id,
    'published',
    '624cb94e-6168-4ed7-97df-46fc552ff002-thumbnail.png'
  ),
  (
    '7a3782da-2928-44f5-9e01-d7075198f9e2',
    'Salt Bread',
    '塩パン',
    'ja',
    'Soft, pillowy Japanese salt bread with a crispy exterior and buttery, savory interior that melts in your mouth',
    'breads',
    'enriched-dough',
    '[{"id":"main","name":"Main","description":"Primary bread ingredients","order":1,"ingredients":[{"name":"Flour T55 Classique","amount":"174","unit":"g","is_flour":true},{"name":"Flour T45 Gruau","amount":"174","unit":"g","is_flour":true},{"name":"Water","amount":"174","unit":"g","is_flour":false},{"name":"Sugar","amount":"17","unit":"g","is_flour":false},{"name":"Yeast","amount":"10","unit":"g","is_flour":false},{"name":"Milk Powder","amount":"17","unit":"g","is_flour":false},{"name":"Salt","amount":"6","unit":"g","is_flour":false},{"name":"Egg","amount":"35","unit":"g","is_flour":false},{"name":"Butter","amount":"6","unit":"g","is_flour":false}]},{"id":"shaping","name":"Shaping","description":"Ingredients for shaping and finishing","order":2,"ingredients":[{"name":"Butter Cube for shaping (10gr/Cube)","amount":"100","unit":"g","is_flour":false},{"name":"Lemon zest","amount":"1","unit":"g","is_flour":false},{"name":"Lime zest","amount":"1","unit":"g","is_flour":false},{"name":"Orange zest","amount":"1","unit":"g","is_flour":false},{"name":"Sea Salt","amount":"1","unit":"g","is_flour":false},{"name":"Clarify Butter","amount":"20","unit":"g","is_flour":false}]}]'::jsonb,
    '[{"step":"1","content":"Mix flour and water on Low speed for 5 minutes."},{"step":"2","content":"Add salt and yeast. Let rest for 10 minutes (autolyse)."},{"step":"3","content":"(PVL mixing) Mix on Low speed for 8 minutes, and continue on High speed for 4 minutes. Target dough temperature: 24 - 26°C.","remark":"PVL (Pétrissage à Vitesse Lente) method ensures proper gluten development without overheating the dough. Monitor dough temperature carefully as enriched doughs can warm quickly."},{"step":"4","content":"Bulk ferment for 15 - 20 minutes at room temperature of 25°C, then overnight fermentation in chiller.","remark":"The overnight fermentation develops better flavor and texture."},{"step":"5","content":"Add a little flour on the bench to stop the dough from sticking. Divide the dough into pieces weighing 60g each."},{"step":"6","content":"Round each piece into a ball.Turn the ball''s seam perpendicular to the bench and roll out a cone shape. Let rest for 15 - 20 minutes."},{"step":"7","content":"Tap the cone shape flat to remove the air. Use a rolling pin to reach a triangle of 7x20 - 25cm."},{"step":"8","content":"Place butter cube on the base of the triangle. Roll the dough to cover the butter, and roll like a croissant.","remark":"Optional: can add zest of lemon, lime, or orange for extra flavor."},{"step":"9","content":"2nd proofing for 1 - 1.5 hours at 28°C with 70% humidity."},{"step":"10","content":"After proofing, spray some water on the top and sprinkle sea salt in the middle of the salt bread."},{"step":"11","content":"Steam the oven. Bake in oven at 200°C for 10 minutes, and then 10 minutes at 180°C."},{"step":"12","content":"Brush with clarify butter and sprinkle directly after baking."},{"step":"13","content":"Let cool for 10 minutes."}]'::jsonb,
    '[{"id":"main-dough","name":"Main Dough Preparation","description":"Prepare the enriched bread dough","order":1,"component_id":"main","steps":["1","2","3","4"]},{"id":"shaping-baking","name":"Shaping & Baking","description":"Shape the salt bread and bake to perfection","order":2,"component_id":"shaping","steps":["5","6","7","8","9","10","11","12","13"]}]'::jsonb,
    '["Preheat oven to 200°C"]'::jsonb,
    690,
    10,
    2,
    user_id,
    'published',
    '7a3782da-2928-44f5-9e01-d7075198f9e2-thumbnail.png'
  ),
  (
    '968932c1-e9e0-442d-a5fb-d6ffc2e054a6',
    'Spritz Cookies',
    'Biscuit Spritz',
    'fr',
    'A classic, buttery cookie with a crispy exterior.',
    'sweets',
    'cookies',
    '[{"id":"main","name":"Main","description":"Primary ingredients","order":1,"ingredients":[{"name":"Butter","amount":"156","unit":"g","is_flour":false},{"name":"Icing sugar","amount":"72","unit":"g","is_flour":false},{"name":"Salt","amount":"2","unit":"g","is_flour":false},{"name":"Vanilla extract","amount":"2","unit":"g","is_flour":false},{"name":"Lemon zest","amount":"1","unit":"pc","is_flour":false},{"name":"Egg white","amount":"30","unit":"g","is_flour":false},{"name":"Flour T55 Classique","amount":"192","unit":"g","is_flour":true},{"name":"Almond powder","amount":"48","unit":"g","is_flour":false}]}]'::jsonb,
    '[{"step":"1","content":"Place softened butter into stand mixer bowl with paddle attachment. Add granulated sugar and start on low speed for 30 seconds to combine.","remark":"Butter should be at room temperature - cold butter won''t cream properly and melted butter won''t hold air."},{"step":"2","content":"Increase speed to medium-high and cream for 3 - 8 minutes. Scrape the bowl frequently every minute or two.","remark":"The mixture will become significantly lighter in color (yellow to pale cream), fluffy, and increased in volume. Texture should be light and airy like whipped cream. Scraping ensures thorough creaming with no unmixed patches."},{"step":"3","content":"Crack eggs into a small bowl. With mixer on medium-low speed, add eggs gradually, mixing well after each addition. Scrape down bowl after all eggs are incorporated.","remark":"The mixture might look curdled initially, but keep mixing until it comes back together and looks smooth before adding more egg."},{"step":"4","content":"Reduce mixer speed to low. Add one-third of dry ingredients, mix until barely combined. Add half the milk/liquid, mix until barely combined. Alternate between dry and wet ingredients until all incorporated. Scrape bowl after each addition.","remark":"Low speed is vital to prevent overmixing and gluten development."},{"step":"5","content":"Remove bowl from mixer. Give batter one or two final gentle folds with rubber spatula.","remark":"This ensures everything at the bottom is incorporated."},{"step":"6","content":"Pipe the batter into 6cm circles on a baking sheet lined with parchment paper. Let rest for 1 hour at room temperature."},{"step":"7","content":"Chill the dough for 1 hour at the refrigerator."},{"step":"8","content":"Bake in convection oven at 165°C for 17 - 19 minutes"},{"step":"9","content":"Optional topping: melted dark chocolate, grated coconut."},{"step":"10","content":"Let cool for 10 minutes."}]'::jsonb,
    NULL,
    '["Preheat oven to 165°C"]'::jsonb,
    158,
    20,
    2,
    user_id,
    'published',
    '968932c1-e9e0-442d-a5fb-d6ffc2e054a6-thumbnail.png'
  ),
  (
    '6d94af12-8dff-4c36-b42a-860ace58094e',
    'White Sandwich Bread',
    'Pain de Mie Blanc',
    'fr',
    'A classic white sandwich bread that is soft, pillowy, and slightly sweet, perfect for sandwiches and toast.',
    'breads',
    'enriched-dough',
    '[{"id":"main","name":"Main","description":"Primary bread ingredients","order":1,"ingredients":[{"name":"Flour T55 Classique","amount":"275","unit":"g","is_flour":true},{"name":"Milk","amount":"193","unit":"g","is_flour":false},{"name":"Salt","amount":"6","unit":"g","is_flour":false},{"name":"Yeast","amount":"4","unit":"g","is_flour":false},{"name":"Sugar","amount":"17","unit":"g","is_flour":false},{"name":"Butter","amount":"47","unit":"g","is_flour":false}]}]'::jsonb,
    '[{"step":"1","content":"(PI mixing) Mix all ingredients on Low speed for 5 minutes, and continue on High speed for 8 minutes. Target dough temperature: 24 to 26°C.","remark":"PI (Pétrissage Intensifié - Intensive Kneading) method uses extended high-speed mixing for maximum gluten development in enriched doughs. The longer high-speed phase creates strong gluten networks essential for soft, fine-textured breads."},{"step":"2","content":"Transfer to a lightly-floured proofing container and cover with a plastic wrap Bulk ferment for 30 minutes at 25°C."},{"step":"3","content":"Divide the dough into pieces weighing 270g each. Round each piece into a ball and let rest for 15 minutes. Shape into a batard. Transfer to a mini loaf pan and let proof for 1 hour at 28°C, humidity 80%.","remark":"Size of dough should be about 40% of the pan."},{"step":"4","content":"Egg wash the batard.","remark":"Be careful not to overdo it, as the egg will seep into the side of the dough and leave burn marks."},{"step":"5","content":"Steam the oven. Bake in convection oven at 150°C (with fan speed 2) for 17 minutes, and at 165°C for 8 minutes."},{"step":"6","content":"Let cool for 10 minutes."}]'::jsonb,
    NULL,
    '["Preheat oven to 150°C"]'::jsonb,
    153,
    1,
    2,
    user_id,
    'published',
    '6d94af12-8dff-4c36-b42a-860ace58094e-thumbnail.png'
  ),
  (
    '9a81e53c-8a5b-49f4-890a-746e47664506',
    '3-Chocolate Scones',
    NULL,
    NULL,
    'Sweet and buttery scones studded with 3 types of chocolate chips, perfect for afternoon tea or a sweet breakfast treat',
    'breads',
    'quick',
    '[{"id":"main","name":"Main","description":"Primary scone ingredients","order":1,"ingredients":[{"name":"Flour T55 Classique","amount":"454","unit":"g","is_flour":true},{"name":"Baking powder","amount":"10","unit":"g","is_flour":false},{"name":"Butter","amount":"197","unit":"g","is_flour":false},{"name":"Salt","amount":"4","unit":"g","is_flour":false},{"name":"Sugar","amount":"130","unit":"g","is_flour":false},{"name":"Whipping cream","amount":"206","unit":"g","is_flour":false},{"name":"Egg","amount":"109","unit":"g","is_flour":false},{"name":"Vanilla extract","amount":"SQ","unit":"g","is_flour":false},{"name":"White chocolate 29%","amount":"105","unit":"g","is_flour":false},{"name":"Milk chocolate 35%","amount":"105","unit":"g","is_flour":false},{"name":"Dark chocolate 70%","amount":"105","unit":"g","is_flour":false}]}]'::jsonb,
    '[{"step":"1","content":"Sablage part 1: Mix the dry ingredients (flour, baking powder, salt, sugar) in a stand mixer at low speed until combined."},{"step":"2","content":"Sablage part 2: Cut butter into small pieces and add, mixing until mixture resembles coarse sand or fine breadcrumbs.","remark":"There should be no large chunks of butter remaining, and the mixture should be uniform."},{"step":"3","content":"Sablage part 3: Add wet ingredients (whipping cream, egg, vanilla extract) to dry ingredients and mix until just combined.","remark":"The mixture should be smooth and cohesive, but not overly wet."},{"step":"4","content":"Roll out the dough into a rectangle (around 20cm x 30cm), wrap it into a plastic wrap, and chill it in the refrigerator for 2 hours (optional)."},{"step":"5","content":"Divide the dough into pieces weighing 85g each. Round each piece into a ball and press it into a circle dough cutter."},{"step":"6","content":"Apply egg wash to the top of the dough."},{"step":"7","content":"Bake in convection oven at 165°C for 25 minutes (at fan speed 4)"},{"step":"8","content":"Apply milk wash to the baked scones. Let cool for 10 minutes."}]'::jsonb,
    NULL,
    '["Preheat convection oven to 165°C"]'::jsonb,
    165,
    10,
    2,
    user_id,
    'published',
    '9a81e53c-8a5b-49f4-890a-746e47664506-thumbnail.png'
  ),
  (
    'c2e17ef1-bb3f-4c60-9e83-0aaadb7472fe',
    'Normandy Bread',
    'Pain Brié',
    'fr',
    'A classic French bread with a unique blonde, striped appearance and a dense crumb. It''s characterized by its blonde crust and dense, tight crumb due to a long kneading and beating process.',
    'breads',
    'enriched-dough',
    '[{"id":"main","name":"Main","description":"Primary bread ingredients","order":1,"ingredients":[{"name":"Flour T55 Tradition","amount":"340","unit":"g","is_flour":true},{"name":"Flour T55 Classique","amount":"340","unit":"g","is_flour":true},{"name":"Water","amount":"258","unit":"g","is_flour":false},{"name":"Yeast","amount":"3","unit":"g","is_flour":false},{"name":"Salt","amount":"12","unit":"g","is_flour":false},{"name":"Fermented dough (e.g. brioche recipe leftovers)","amount":"204","unit":"g","is_flour":false},{"name":"Butter","amount":"75","unit":"g","is_flour":false},{"name":"Sugar","amount":"41","unit":"g","is_flour":false}]}]'::jsonb,
    '[{"step":"1","content":"Mix flour and water on Low speed for 5 minutes."},{"step":"2","content":"Add salt and yeast. Let rest for 10 minutes (autolyse)."},{"step":"3","content":"(PA mixing) Mix on Low speed for 5 minutes, and continue on High speed for 5 minutes. Target dough temperature: 24 to 26°C.","remark":"PA (Pétrissage Amélioré - Improved Kneading) method provides moderate gluten development ideal for lean doughs like baguettes. The shorter high-speed phase prevents overheating while achieving proper dough structure."},{"step":"4","content":"Transfer to a lightly-floured proofing container and cover with a plastic wrap. Bulk ferment for 30 minutes."},{"step":"5","content":"Divide the dough into pieces weighing 315g each. Shape into a bâtard. Let rest for 15 minutes. "},{"step":"6","content":"Apply egg wash to the top of the dough."},{"step":"7","content":"Score 5 parallel lines, spaced roughly equally on the dough lengthwise by 5mm."},{"step":"8","content":"Proof at 27°C, humidity 80% for 75 minutes."},{"step":"9","content":"Bake in oven at 210°C for 30 - 40 minutes (deck oven heat distribution Top 50%/Front 60%/Bottom 30%). Damper 10 minutes before finishing baking."},{"step":"10","content":"Let cool for 10 minutes."}]'::jsonb,
    NULL,
    '["Preheat deck oven to 210°C"]'::jsonb,
    210,
    2,
    2,
    user_id,
    'published',
    'c2e17ef1-bb3f-4c60-9e83-0aaadb7472fe-thumbnail.png'
  ),
  (
    '2e017edc-7e32-43dc-a299-05b4c1fc3200',
    'Viennese Bread',
    'Pain Viennois',
    'fr',
    'An Austrian bread traditionally made in the shape of a baguette, but with a softer crust and finer, sweeter texture than classic French baguette. This bread is ideal for toasting and making sandwiches.',
    'breads',
    'enriched-dough',
    '[{"id":"main","name":"Main","description":"Primary bread ingredients","order":1,"ingredients":[{"name":"Flour T55 Tradition","amount":"163","unit":"g","is_flour":true},{"name":"Flour T55 Classique","amount":"163","unit":"g","is_flour":true},{"name":"Water","amount":"140","unit":"g","is_flour":false},{"name":"Egg","amount":"39","unit":"g","is_flour":false},{"name":"Salt","amount":"8","unit":"g","is_flour":false},{"name":"Yeast","amount":"7","unit":"g","is_flour":false},{"name":"Milk powder","amount":"21","unit":"g","is_flour":false},{"name":"Sugar","amount":"29","unit":"g","is_flour":false},{"name":"Butter","amount":"36","unit":"g","is_flour":false},{"name":"Lemon zest","amount":"0.3","unit":"pc","is_flour":false}]},{"id":"toppings","name":"Toppings","description":"Optional toppings","order":2,"ingredients":[{"name":"White sesame seeds","amount":"10","unit":"g","is_flour":false},{"name":"Black sesame seeds","amount":"10","unit":"g","is_flour":false},{"name":"Poppy seeds","amount":"10","unit":"g","is_flour":false}]}]'::jsonb,
    '[{"step":"1","content":"Mix flour and water on Low speed for 5 minutes."},{"step":"2","content":"Add salt and yeast. Let rest for 10 minutes (autolyse)."},{"step":"3","content":"(PI mixing) Mix on Low speed for 5 minutes, and continue on High speed for 8 minutes. Target dough temperature: 24 to 26°C.","remark":"PI (Pétrissage Intensifié - Intensive Kneading) method uses extended high-speed mixing for maximum gluten development in enriched doughs. The longer high-speed phase creates strong gluten networks essential for soft, fine-textured breads."},{"step":"4","content":"Transfer to a lightly-floured proofing container and cover with a plastic wrap. Bulk ferment for 30 minutes."},{"step":"5","content":"Divide the dough into pieces weighing 150g each. Shape into a baguette. Let rest for 15 minutes."},{"step":"6","content":"Apply egg wash to the top of the dough. Dip the dough in your choice of toppings (black or white sesame seeds, or poppy seeds)."},{"step":"7","content":"Score 7 sausage cuts. Transfer to a baking tray."},{"step":"8","content":"Proof at 28°C, humidity 80% for 70 minutes."},{"step":"9","content":"Bake in deck oven at 210°C for 18 - 20 minutes (deck oven heat distribution Top 80%/Front 60%/Bottom 20%), or 180°C in convection oven for 15 - 18 minutes."},{"step":"10","content":"Let cool for 10 minutes."}]'::jsonb,
    NULL,
    '["Preheat deck oven to 210°C"]'::jsonb,
    178,
    2,
    2,
    user_id,
    'published',
    '2e017edc-7e32-43dc-a299-05b4c1fc3200-thumbnail.png'
  ),
  (
    'e5d77804-d7da-48de-9ed0-f2b64e8c4791',
    'Milk Bread',
    'Pain au Lait',
    'fr',
    'A traditional French milk bread with a tender, pillowy crumb and subtle sweetness. Made with milk powder and enriched with butter and eggs, this bread has a golden crust and soft interior that''s perfect for breakfast, afternoon tea, or as a base for sweet or savory sandwiches.',
    'breads',
    'enriched-dough',
    '[{"id":"main","name":"Main","description":"Primary bread ingredients","order":1,"ingredients":[{"name":"Flour T45 Gruau","amount":"218","unit":"g","is_flour":true},{"name":"Flour T55 Classique","amount":"218","unit":"g","is_flour":true},{"name":"Milk","amount":"196","unit":"g","is_flour":false},{"name":"Egg","amount":"68","unit":"g","is_flour":false},{"name":"Salt","amount":"9","unit":"g","is_flour":false},{"name":"Yeast","amount":"18","unit":"g","is_flour":false},{"name":"Sugar","amount":"53","unit":"g","is_flour":false},{"name":"Butter","amount":"131","unit":"g","is_flour":false}]},{"id":"toppings","name":"Toppings","description":"Optional toppings","order":2,"ingredients":[{"name":"Sugar nibs","amount":"10","unit":"g","is_flour":false},{"name":"Almond sticks","amount":"10","unit":"g","is_flour":false}]}]'::jsonb,
    '[{"step":"1","content":"Mix flour and water on Low speed for 5 minutes."},{"step":"2","content":"Add salt and yeast. Let rest for 10 minutes (autolyse)."},{"step":"3","content":"(PI mixing) Mix in the rest of the ingredients on Low speed for 5 minutes, and continue on High speed for 8 minutes. Target dough temperature: 24 to 26°C.","remark":"PI (Pétrissage Intensifié - Intensive Kneading) method uses extended high-speed mixing for maximum gluten development in enriched doughs. The longer high-speed phase creates strong gluten networks essential for soft, fine-textured breads."},{"step":"4","content":"Transfer to a lightly-floured proofing container and cover with a plastic wrap. Bulk ferment for 20 minutes."},{"step":"5","content":"Chill in the fridge overnight."},{"step":"6","content":"Divide the dough into 12 pieces of 30g each (for Nanterre loaf), and 12 pieces of 45g each (for single strand braid). Pre-shape all of them into loose balls."},{"step":"7","content":"(For Nanterre loaf) Place 6 balls into each loaf pan in a zigzag pattern. (For single strand braid) Braid the 12 pieces into a single strand braid."},{"step":"8","content":"Apply egg wash to the top of the loaves and braids."},{"step":"9","content":"(optional) Apply toppings to the top of the loaves and braids."},{"step":"10","content":"Proof at 28°C, humidity 80% for 40 minutes."},{"step":"11","content":"Bake in convection oven at 150 - 155°C for 8 - 12 minutes for single-strand braid, and 155°C for 25 - 30 minutes for Nanterre loaf."},{"step":"12","content":"Let cool for 10 minutes."}]'::jsonb,
    NULL,
    '["Preheat convection oven to 150 - 155°C for single-strand braid, and 155°C for Nanterre loaf"]'::jsonb,
    158,
    2,
    2,
    user_id,
    'published',
    'e5d77804-d7da-48de-9ed0-f2b64e8c4791-thumbnail.png'
  ),
  (
    'a7dabebe-8839-43f4-b4e7-44972d4d57c5',
    'Hot Dog Buns',
    NULL,
    NULL,
    'Soft and pillowy hot dog buns with a tender crumb. These enriched dough buns are perfect for holding your favorite sausages, hot dogs, or bratwurst. The slightly sweet flavor and sturdy yet gentle texture makes them ideal for any casual meal.',
    'breads',
    'enriched-dough',
    '[{"id":"main","name":"Main","description":"Primary bread ingredients","order":1,"ingredients":[{"name":"Flour T45 Gruau","amount":"564","unit":"g","is_flour":true},{"name":"Flour T55 Classique","amount":"564","unit":"g","is_flour":true},{"name":"Water","amount":"305","unit":"g","is_flour":false},{"name":"Milk","amount":"305","unit":"g","is_flour":false},{"name":"Egg","amount":"112","unit":"g","is_flour":false},{"name":"Yeast","amount":"22","unit":"g","is_flour":false},{"name":"Sugar","amount":"136","unit":"g","is_flour":false},{"name":"Salt","amount":"22","unit":"g","is_flour":false},{"name":"Shortening","amount":"133","unit":"g","is_flour":false}]},{"id":"fillings","name":"Fillings","description":"","order":2,"ingredients":[{"name":"Beef hot dog sausage 6 inch","amount":"24","unit":"pc","is_flour":false},{"name":"Caramelized red onion","amount":"600","unit":"g","is_flour":false},{"name":"Fried Onion","amount":"240","unit":"g","is_flour":false},{"name":"Midi Red Sorrel flower","amount":"288","unit":"pcs","is_flour":false},{"name":"French yellow mustard","amount":"SQ","unit":"SQ","is_flour":false},{"name":"Tomato ketchup","amount":"SQ","unit":"SQ","is_flour":false}]}]'::jsonb,
    '[{"step":"1","content":"(PI mixing) Mix all ingredients except for the shortening on Low speed for 5 minutes, then for another 8 minutes on High speed.","remark":"PI (Pétrissage Intensifié - Intensive Kneading) method uses extended high-speed mixing for maximum gluten development in enriched doughs. The longer high-speed phase creates strong gluten networks essential for soft, fine-textured breads."},{"step":"2","content":"Add shortening. Continue mixing on High speed for another 2 minutes. Target dough temperature: 24 to 26°C."},{"step":"3","content":"Transfer to a lightly-floured proofing container and cover with a plastic wrap. Bulk ferment for minimum 30 minutes.","remark":"Check for gluten development using the window pane test."},{"step":"4","content":"Divide the dough into 6 pieces of 90g each. Pre-shape all of them into rolls. Let rest for 15 minutes."},{"step":"5","content":"Shape each dough into a batard. Transfer to a baguette tray."},{"step":"6","content":"Proof at 28°C, humidity 80% for 30 - 40 minutes."},{"step":"7","content":"Apply egg wash to the top of the rolls."},{"step":"8","content":"Bake in convection oven at 180°C for 10 - 12 minutes, or deck oven at 200°C for 10 - 15 minutes.","remark":"Deck oven heat distribution: Top 80%/ Front 60%/ Bottom 20%"},{"step":"9","content":"Let cool for 10 minutes."},{"step":"10","content":"Steam the hot dog bun for 3 - 5 minutes to soften the texture. Lightly poach the hot dog in stock or water for 5 minutes."},{"step":"11","content":"Cut the middle of the hot dog bun. Spread mustard inside of the bread. Add caramelized onion slices, then place the hot dog sausage in between."},{"step":"12","content":"Finish with French yellow mustard and tomato ketchup drizzle on top and fried onion and flower."}]'::jsonb,
    NULL,
    '["Preheat convection oven to 180°C"]'::jsonb,
    118,
    12,
    2,
    user_id,
    'published',
    'a7dabebe-8839-43f4-b4e7-44972d4d57c5-thumbnail.png'
  ),
  (
    '676ef542-a65c-4422-9e11-4f1bb435587d',
    'Melon Pan',
    'メロンパン',
    'ja',
    'A Japanese sweet bread featuring a tender, fluffy interior wrapped in a crispy, cookie-like shell. Despite its name, melon pan traditionally doesn''t contain melon but gets its name from the distinctive crosshatch pattern on top that resembles a cantaloupe.',
    'breads',
    'enriched-dough',
    '[{"id":"covering-dough","name":"Covering dough","description":"The cookie-like shell that wraps the sweet bread.","order":1,"ingredients":[{"name":"Butter","amount":"84","unit":"g","is_flour":false},{"name":"Sugar","amount":"156","unit":"g","is_flour":false},{"name":"Egg","amount":"84","unit":"g","is_flour":false},{"name":"Vanilla extract","amount":"5","unit":"g","is_flour":false},{"name":"Lemon Zest","amount":"1","unit":"pc","is_flour":false},{"name":"Flour T55 Classique","amount":"288","unit":"g","is_flour":true}]},{"id":"main-dough","name":"Main dough","description":"The tender, fluffy bread base for melon pan.","order":2,"ingredients":[{"name":"Flour T45 Gruau","amount":"211","unit":"g","is_flour":true},{"name":"Flour T55 Classique","amount":"211","unit":"g","is_flour":true},{"name":"Sugar","amount":"76","unit":"g","is_flour":false},{"name":"Salt","amount":"9","unit":"g","is_flour":false},{"name":"Milk powder","amount":"15","unit":"g","is_flour":false},{"name":"Yeast","amount":"24","unit":"g","is_flour":false},{"name":"Egg","amount":"45","unit":"g","is_flour":false},{"name":"Water","amount":"211","unit":"g","is_flour":false},{"name":"Butter","amount":"45","unit":"g","is_flour":false}]}]'::jsonb,
    '[{"step":"1","content":"Crémage butter and sugar till fluffy.","remark":"Butter should be softened, but not melted. Crémage helps to incorporate air into the dough."},{"step":"2","content":"Add the eggs in part by part, then add the vanilla extract.","remark":"Be careful not to add the eggs too fast; it will cause the water and fats to separate. Mix until the eggs are fully incorporated before adding more."},{"step":"3","content":"Add the flour in part by part, then add the lemon zest."},{"step":"4","content":"Chill in the fridge for 30 minutes.","remark":"We need the dough to be cold and hard to cut it out easily."},{"step":"5","content":"Roll out the dough into a rectangle (30 x 40cm) between 2 baking papers."},{"step":"6","content":"Cut the dough into 12 pieces of 12 - 14cm diameter each."},{"step":"7","content":"(PI mixing) Mix all ingredients on Low speed for 5 minutes, then for another 8 - 13 minutes on Medium speed until the gluten network is developed.","remark":"PI mixing is suited for maximum gluten development in enriched doughs where extreme softness and a fine crumb is desired. Check gluten development using the window pane test."},{"step":"8","content":"Bulk ferment for 60 minutes at 25°C."},{"step":"9","content":"Divide the dough into 12 pieces of 70g each. Pre-shape all of them into balls. Let rest for 15 minutes."},{"step":"10","content":"Tighten the balls."},{"step":"11","content":"Place the covering doughs on top of the balls and tighten the doughs over the balls completely.","remark":"The covering dough should cover only the top of the balls and some, but not the entire bottom of the balls."},{"step":"12","content":"Score the top of the balls with a pattern using the rounded side of a plastic scraper."},{"step":"13","content":"Proof at 25°C, humidity 70% for 60 minutes."},{"step":"14","content":"Apply egg wash to the top of the balls. Sprinkle some sugar on top of the balls."},{"step":"15","content":"Bake in convection oven at 150 - 165°C for 12 - 15 minutes"},{"step":"16","content":"Let cool for 10 minutes."}]'::jsonb,
    '[{"id":"covering-dough","name":"Covering Dough Preparation","description":"Create the cookie-like shell that wraps the sweet bread","order":1,"component_id":"covering-dough","steps":["1","2","3","4","5","6"]},{"id":"main-dough","name":"Main Dough & Assembly","description":"Prepare the bread base and assemble the melon pan","order":2,"component_id":"main-dough","steps":["7","8","9","10","11","12","13","14","15","16"]}]'::jsonb,
    '["Preheat convection oven to 150 - 165°C"]'::jsonb,
    220,
    12,
    3,
    user_id,
    'published',
    '676ef542-a65c-4422-9e11-4f1bb435587d-thumbnail.png'
  ),
  (
    'b8c9d0e1-f2a3-4b5c-6d7e-8f9a0b1c2d3e',
    'Butter Croissant',
    'Croissant au Beurre',
    'fr',
    'Classic French laminated pastry with flaky, buttery layers. Made using traditional folding techniques to create the signature airy texture and golden crust.',
    'breads',
    'enriched-dough',
    '[{"id":"main-dough","name":"Main Dough","description":"Base dough for croissants","order":1,"ingredients":[{"name":"Flour T45 Gruau","amount":"300","unit":"g","is_flour":true},{"name":"Flour T55 Classique","amount":"300","unit":"g","is_flour":true},{"name":"Water","amount":"294","unit":"g","is_flour":false},{"name":"Yeast","amount":"27","unit":"g","is_flour":false},{"name":"Salt","amount":"13","unit":"g","is_flour":false},{"name":"Sugar","amount":"78","unit":"g","is_flour":false},{"name":"Milk powder","amount":"12","unit":"g","is_flour":false}]},{"id":"butter-block","name":"Butter Block","description":"Dry butter for lamination","order":2,"ingredients":[{"name":"Dry butter","amount":"300","unit":"g","is_flour":false}]}]'::jsonb,
    '[{"step":"1","content":"(PVL mixing) Mix all main dough ingredients on Low speed for 8 minutes, then continue on High speed for 3 minutes. Target dough temperature: 24°C - 26°C.","remark":"PVL (Pétrissage à Vitesse Lente) method ensures proper gluten development without overheating the dough. Monitor dough temperature carefully as enriched doughs can warm quickly."},{"step":"2","content":"Bulk ferment for 15 - 20 minutes at room temperature."},{"step":"3","content":"Divide the dough 2 pieces of 510g each. Flatten each piece into a 20x30cm rectangle. Keep overnight in the refrigerator."},{"step":"4","content":"Shape the dry butter into a 20x15cm rectangle and place it at the center of the 20x30cm dough."},{"step":"5","content":"Cut out both sides of the dough (that has no butter on it), and stack them on top of the butter. Roll out the dough lengthwise (you should be rolling parallel to the seam from the stacking). If the butter is starting to becoming soft, put it back in the freezer for 20 minutes."},{"step":"6","content":"Perform a double fold: Along the lengthwise, mentally divide the dough into 6 equal parts. Fold over the left 1/6 to cover the 2/6 area. Then, bring the outer edge of the dough from the right side to meet this folded edge. Then, fold this entire folded dough into half, like closing a book."},{"step":"7","content":"Freeze for about 20 minutes to firm up the butter layers."},{"step":"8","content":"Perform a single fold: Along the lengthwise, mentally divide the dough into 3 equal parts. Fold over the left 1/3 to cover the middle 1/3. Then, fold over the right 1/3 to cover the middle 1/3. Total thickness should be ≤ 1 inch."},{"step":"9","content":"Freeze for about 20 minutes to maintain butter consistency."},{"step":"10","content":"Roll out the dough into a 32x30cm rectangle. Along the length of the dough, mark out the 4.5cm, 13.5cm, 22.5cm on the top of the dough. Then, mark out the 9cm, 18cm, 27cm on the bottom of the dough. Using these marks as guidelines, cut out 5 triangles, each of base 9cm and height 30cm."},{"step":"11","content":"Roll each triangle from the wide base toward the point, stretching slightly to achieve the classic crescent shape. Place seam-side down on baking sheets.","remark":"Make sure to press down the tip of the triangle into the bottom of the croissant and make it flat. Otherwise the croissant will be tilted to one side and cause uneven proofing and subsequently, an unevenly-shaped croissant."},{"step":"12","content":"2nd proofing: Proof for 1:30 - 2 hours at 28°C with 80% humidity."},{"step":"13","content":"Apply egg wash to the surface of the croissants."},{"step":"14","content":"Bake in convection oven at 165°C for 16 - 18 minutes until golden brown."}]'::jsonb,
    '[{"id":"dough-preparation","name":"Dough Preparation","description":"Prepare and rest the main dough","order":1,"component_id":"main-dough","steps":["1","2","3"]},{"id":"lamination","name":"Lamination Process","description":"Incorporate butter and create layers through folding","order":2,"component_id":"butter-block","steps":["4","5","6","7","8","9"]},{"id":"shaping","name":"Shaping","description":"Shape the croissants","order":3,"component_id":"main-dough","steps":["10","11"]},{"id":"final-proofing-baking","name":"Final Proofing & Baking","description":"Final proofing and baking to golden perfection","order":4,"component_id":"main-dough","steps":["12","13","14"]}]'::jsonb,
    '["Preheat convection oven to 165°C"]'::jsonb,
    238,
    10,
    3,
    user_id,
    'published',
    'b8c9d0e1-f2a3-4b5c-6d7e-8f9a0b1c2d3e-thumbnail.png'
  ),
  (
    'c3d4e5f6-a7b8-9c0d-1e2f-3a4b5c6d7e8f',
    'Grissini',
    'Grissini',
    'it',
    'Traditional Italian breadsticks with a crispy texture and herbed flavor. These thin, crunchy sticks are perfect as appetizers, with dips, or alongside soups and salads.',
    'breads',
    'lean-dough',
    '[{"id":"prefermentation","name":"Prefermentation","description":"Pre-fermented dough for enhanced flavor","order":1,"ingredients":[{"name":"Flour T55 Classique","amount":"35","unit":"g","is_flour":true},{"name":"Water","amount":"24","unit":"g","is_flour":false},{"name":"Yeast","amount":"4","unit":"g","is_flour":false},{"name":"Sugar","amount":"2","unit":"g","is_flour":false}]},{"id":"main-dough","name":"Main Dough","description":"Primary dough ingredients","order":2,"ingredients":[{"name":"Prefermentation","amount":"64","unit":"g","is_flour":false},{"name":"Flour T55 Classique","amount":"248","unit":"g","is_flour":true},{"name":"Water","amount":"89","unit":"g","is_flour":false},{"name":"Salt","amount":"6","unit":"g","is_flour":false},{"name":"Sugar","amount":"15","unit":"g","is_flour":false},{"name":"Olive oil","amount":"44","unit":"g","is_flour":false},{"name":"Provence herbs","amount":"8","unit":"g","is_flour":false}]},{"id":"dusting","name":"Dusting","description":"For shaping and finishing","order":3,"ingredients":[{"name":"Semolina flour","amount":"SQ","unit":"","is_flour":false}]}]'::jsonb,
    '[{"step":"1","content":"Mix all prefermentation ingredients and let proof for 1 - 2 hours at room temperature.","remark":"This is a Biga prefermentation, commmonly referred to as an Italian preferment. It adds complexity to the flavor and improves the texture of the final product."},{"step":"2","content":"(PA mixing) Mix the prefermentation with all main dough ingredients on Low speed for 5 minutes, then continue on High speed for 5 minutes. Target dough temperature: 24°C - 26°C.","remark":"PA (Pétrissage Amélioré - Improved Kneading) method provides moderate gluten development ideal for lean doughs like baguettes. The shorter high-speed phase prevents overheating while achieving proper dough structure."},{"step":"3","content":"Bulk ferment for 10 - 20 minutes at room temperature."},{"step":"4","content":"Roll out the dough to 2mm thickness in a rectangle approximately 30x40cm, using a plastic wrap as a guide."},{"step":"5","content":"Rest the rolled dough for 10 minutes in blast chiller to firm up.","remark":"Chilling makes the dough easier to cut cleanly without tearing."},{"step":"6","content":"Cut the dough into strips 1cm thick. Dust each strip with semolina flour, and shape to your liking. You can twist it, make it into a knot, or leave it as a long stick.","remark":"Use a sharp knife or pizza cutter for clean cuts. The semolina prevents sticking and adds texture."},{"step":"7","content":"2nd proofing: Proof for 40 - 50 minutes at 28°C with 80% humidity."},{"step":"8","content":"Bake in convection oven at 160°C for 18 - 22 minutes until golden and crispy. Optional: Open the oven damper 5 minutes before the end of baking for extra crispiness.","remark":"Opening the damper helps achieve maximum crispiness."}]'::jsonb,
    '[{"id":"prefermentation","name":"Prefermentation","description":"Prepare the pre-fermented dough","order":1,"component_id":"prefermentation","steps":["1"]},{"id":"main-dough","name":"Main Dough Preparation","description":"Mix and develop the main dough","order":2,"component_id":"main-dough","steps":["2","3"]},{"id":"shaping-proofing","name":"Shaping & Proofing","description":"Shape the grissini and final proofing","order":3,"component_id":"dusting","steps":["4","5","6","7"]},{"id":"baking","name":"Baking","description":"Bake to golden crispy perfection","order":4,"component_id":"main-dough","steps":["8"]}]'::jsonb,
    '["Preheat convection oven to 160°C"]'::jsonb,
    240,
    40,
    2,
    user_id,
    'published',
    'c3d4e5f6-a7b8-9c0d-1e2f-3a4b5c6d7e8f-thumbnail.png'
  ),
  (
    'd5e6f7a8-b9c0-1d2e-3f4a-5b6c7d8e9f0a',
    'Raisin Danish',
    'Pain aux Raisins',
    'fr',
    'Classic French laminated pastry filled with pastry cream and overnight-soaked raisins, finished with a shiny syrup glaze',
    'breads',
    'enriched-dough',
    '[{"id":"main-dough","name":"Main Dough","description":"Base enriched dough for lamination","order":1,"ingredients":[{"name":"Flour T45 Gruau","amount":"256","unit":"g","is_flour":true},{"name":"Flour T55 Classique","amount":"256","unit":"g","is_flour":true},{"name":"Milk","amount":"189","unit":"g","is_flour":false},{"name":"Egg","amount":"84","unit":"g","is_flour":false},{"name":"Salt","amount":"10","unit":"g","is_flour":false},{"name":"Yeast","amount":"20","unit":"g","is_flour":false},{"name":"Sugar","amount":"51","unit":"g","is_flour":false},{"name":"Butter","amount":"20","unit":"g","is_flour":false}]},{"id":"butter-block","name":"Butter Block","description":"Dry butter for lamination","order":2,"ingredients":[{"name":"Dry butter","amount":"256","unit":"g","is_flour":false}]},{"id":"pastry-cream","name":"Pastry Cream","description":"Crème Pâtissière for filling","order":3,"ingredients":[{"name":"Milk","amount":"200","unit":"g","is_flour":false},{"name":"Sugar (1)","amount":"20","unit":"g","is_flour":false},{"name":"Vanilla extract","amount":"SQ","unit":"","is_flour":false},{"name":"Sugar (2)","amount":"20","unit":"g","is_flour":false},{"name":"Egg yolk","amount":"64","unit":"g","is_flour":false},{"name":"Cream powder","amount":"21","unit":"g","is_flour":false},{"name":"Butter","amount":"24","unit":"g","is_flour":false}]},{"id":"filling","name":"Filling","description":"Rum-soaked raisins","order":4,"ingredients":[{"name":"Dark raisin, soaked in rum (overnight)","amount":"150","unit":"g","is_flour":false}]},{"id":"syrup","name":"Shiny Syrup","description":"Finishing glaze","order":5,"ingredients":[{"name":"Water","amount":"100","unit":"g","is_flour":false},{"name":"Sugar","amount":"100","unit":"g","is_flour":false}]}]'::jsonb,
    '[{"step":"1","content":"Mix the milk with first portion of sugar and vanilla extract in a saucepan, and bring to a gentle boil.","remark":"Don''t let it boil over vigorously. A rolling boil can scorch the milk at the bottom of the pan, leading to off-flavors. Adding some sugar to the milk helps prevent a skin from forming on the surface as it heats"},{"step":"2","content":"In a separate bowl, mix the second portion of sugar with cream powder, then whisk (blanchir) the egg yolks in until the mixture turns pale yellow, thickens slightly, and falls in a ribbon from the whisk.","remark":"Blanchir (pronounced \"blahn-sheer\") refers to the process of whisking the egg yolks with sugar until they become pale. This helps to aerate the yolks, creating a stable foam that adds volume and lightness to the final product."},{"step":"3","content":"Tempering: While whisking the egg yolk mixture continuously, slowly pour about one-third to half of the hot milk into it. This gradually raises the temperature of the egg yolks without cooking them. Once tempered, pour the entire tempered mixture back into the saucepan with the remaining hot milk. Cook over medium heat, whisking constantly and vigorously, especially paying attention to the bottom and corners of the pot where the mixture can stick and scorch, until the mixture comes to a full boil and visibly thickens."},{"step":"4","content":"Add the butter immediately after removing the cream from the heat. Whisk vigorously until the butter is fully melted and incorporated. This adds richness, gloss, and a silky smooth texture. It also helps prevent a skin from forming as the cream cools.","remark":"Use cold, cubed butter. It melts quickly and helps cool the cream slightly."},{"step":"5","content":"Pour the hot pastry cream into a shallow tray, dish, or a baking sheet. Spreading it thinly maximizes the surface area for cooling. Immediately cover the surface of the cream directly with plastic wrap. Press the plastic wrap down so it touches the entire surface of the cream. This prevents a skin from forming and traps moisture. Cool down quickly on a refrigerator tray until 4°C.","remark":"Rapid cooling to 4°C prevents bacterial growth and maintains smooth texture."},{"step":"6","content":"(PVL mixing) Mix all main dough ingredients on Low speed for 8 minutes, then continue on High speed for 3 minutes. Target dough temperature: 24°C - 26°C.","remark":"PVL (Pétrissage à Vitesse Lente) method ensures proper gluten development without overheating the dough. Monitor dough temperature carefully as enriched doughs can warm quickly."},{"step":"7","content":"1st proofing: Bulk ferment for 15 - 25 minutes at room temperature."},{"step":"8","content":"Flatten the dough into a 20x30cm rectangle. Freeze overnight.","remark":"Freezing helps firm the dough for easier lamination."},{"step":"9","content":"Shape the dry butter (256g) into a 20x15cm rectangle and place it at the center of the rectangle dough."},{"step":"10","content":"Lamination: Cut out both sides of the dough (that has no butter on it), and stack them on top of the butter. Roll out the dough lengthwise (you should be rolling parallel to the seam from the stacking). Perform a double fold; along the lengthwise, mentally divide the dough into 6 equal parts. Fold over the left 1/6 to cover the 2/6 area. Then, bring the outer edge of the dough from the right side to meet this folded edge. Then, fold this entire folded dough into half, like closing a book. Then, perform a single fold; along the lengthwise, mentally divide the dough into 3 equal parts. Fold over the left 1/3 to cover the middle 1/3. Then, fold over the right 1/3 to cover the middle 1/3. Roll it out into 30x45cm with 2.5mm thickness.","remark":"If using a dough sheeter, roll the dough with 25mm, then 20mm, 15mm, 12mm, 10mm, 8mm, 7mm, then do a double fold. Rotate the dough 90°. Then, roll the dough with 25mm, 20mm, ... 3mm, then do a single fold to achieve the same result."},{"step":"11","content":"Freeze for minimum 25 minutes."},{"step":"12","content":"Bring the pastry cream out of the refrigerator and whisk it vigorously (or use a stand mixer with a whisk attachment) to smooth it out and return it to a pipeable consistency. It will become silky and light again.","remark":"When the pastry cream is thoroughly chilled, it will be very firm and hard to spread onto the dough."},{"step":"13","content":"Shaping Part 1: Add the prepared pastry cream on top of the 30x45cm dough sheet, and spread it out with a big spatula, leaving about 3 - 5cm of space at one end to allow the dough to stick after rolling it up. Apply water to this area. Then, spread the macerated dark raisins evenly over the pastry cream. Roll the dough into a roll, and wrap it in a baking sheet. Place seam down after shaping."},{"step":"14","content":"Chill the roll in the refrigerator for 10 minutes."},{"step":"15","content":"Shaping Part 2: Trim the edges of the roll using a knife to get clean and neat edges. Make marks at 3cm, 6cm, ..., 27cm along the roll, and cut the into pieces of 3cm each. Transfer to baking sheet.","remark":"To prevent the roll from unrolling itself later on due to the pastry cream, you may undo the end of the roll and stick it to the bottom."},{"step":"16","content":"2nd proofing: Proof for 60 - 70 minutes at 28°C with 80% humidity."},{"step":"17","content":"Optional: Apply egg wash before baking."},{"step":"18","content":"Bake in convection oven at 155°C for 18 to 20 minutes until golden brown."},{"step":"19","content":"Finishing: Glaze with shiny syrup immediately after baking.","remark":"The syrup should be applied while both the pastry and syrup are hot for best absorption and shine."}]'::jsonb,
    '[{"id":"pastry-cream-preparation","name":"Pastry Cream Preparation","description":"Prepare the crème pâtissière filling","order":1,"component_id":"pastry-cream","steps":["1","2","3","4","5"]},{"id":"dough-preparation","name":"Dough Preparation & First Proof","description":"Prepare the enriched dough and first proofing","order":2,"component_id":"main-dough","steps":["6","7","8"]},{"id":"lamination","name":"Lamination Process","description":"Incorporate butter and create layers through folding","order":3,"component_id":"butter-block","steps":["9","10","11"]},{"id":"shaping-proofing","name":"Shaping & Second Proofing","description":"Shape the pastries and final proofing","order":4,"component_id":"filling","steps":["12","13","14","15","16"]},{"id":"baking-finishing","name":"Baking & Finishing","description":"Bake and finish with shiny syrup","order":5,"component_id":"syrup","steps":["17","18","19"]}]'::jsonb,
    '["Preheat convection oven to 155°C","Soak raisins in rum overnight","Prepare the finishing glaze by boiling water and sugar together"]'::jsonb,
    180,
    12,
    3,
    user_id,
    'published',
    'd5e6f7a8-b9c0-1d2e-3f4a-5b6c7d8e9f0a-thumbnail.png'
  ),
  (
    'f1a2b3c4-d5e6-7f8a-9b0c-1d2e3f4a5b6c',
    'Bacon Fougasse',
    'Fougasse au Bacon',
    'fr',
    'Traditional French flatbread shaped like a leaf with crispy smoked bacon pieces, brushed with aromatic herb-infused olive oil',
    'breads',
    'lean-dough',
    '[{"id":"main-dough","name":"Main Dough","description":"Primary bread ingredients with bacon","order":1,"ingredients":[{"name":"Flour T55 Classique","amount":"583","unit":"g","is_flour":true},{"name":"Water","amount":"382","unit":"g","is_flour":false},{"name":"Salt","amount":"12","unit":"g","is_flour":false},{"name":"Yeast","amount":"9","unit":"g","is_flour":false},{"name":"Sugar","amount":"12","unit":"g","is_flour":false},{"name":"Fermented dough","amount":"115","unit":"g","is_flour":false},{"name":"Smoked bacon","amount":"175","unit":"g","is_flour":false}]},{"id":"finishing","name":"Finishing","description":"Aromatic oil for brushing","order":2,"ingredients":[{"name":"Olive oil","amount":"SQ","unit":"","is_flour":false},{"name":"Garlic, crushed","amount":"SQ","unit":"","is_flour":false},{"name":"Oregano","amount":"SQ","unit":"","is_flour":false},{"name":"Rosemary","amount":"SQ","unit":"","is_flour":false}]}]'::jsonb,
    '[{"step":"1","content":"(PA mixing) Mix all main dough ingredients, except for smoked bacon, on Low speed for 5 minutes, then continue on High speed for 5 minutes. Add smoked bacon and mix until combined. Target dough temperature: 24°C - 26°C.","remark":"PA (Pétrissage Amélioré - Improved Kneading) method provides moderate gluten development ideal for lean doughs like baguettes. The shorter high-speed phase prevents overheating while achieving proper dough structure."},{"step":"2","content":"1st proofing: Bulk ferment for 45 - 55 minutes at room temperature."},{"step":"3","content":"Divide the dough into 4 pieces of 320g each. Shape each piece into a ball. Let rest for 10-15 minutes."},{"step":"4","content":"Shape each piece into a fougasse (traditional leaf pattern). Proof on couche with 2 pieces per couche.","remark":"The cutting of the pattern is in a later step."},{"step":"5","content":"2nd proofing: Proof for 60 - 70 minutes at 25°C with 70% humidity. Transfer to a baking paper on a wooden board.","remark":"The fougasse should have increased in size but still hold its leaf shape."},{"step":"6","content":"Cut the dough in a leaf pattern to create the characteristic fougasse openings. You may use the rounded side of a dough scraper to create the openings.","remark":"Make clean cuts that go all the way through the dough to create the distinctive holes."},{"step":"7","content":"Bake in deck oven at 260°C for 9 to 12 minutes.","remark":"Deck oven heat distribution: Top 80%/ front 60%/ bottom 20%"},{"step":"8","content":"Brush the fougasse with aromatic olive oil mixture immediately after baking.","remark":"The hot bread will absorb the flavored oil better, creating a more aromatic crust."}]'::jsonb,
    '[{"id":"dough-preparation","name":"Dough Preparation & First Proof","description":"Mix the dough and first proofing","order":1,"component_id":"main-dough","steps":["1","2"]},{"id":"shaping-proofing","name":"Scaling, Shaping & Second Proof","description":"Scale, shape into fougasse and final proofing","order":2,"component_id":"main-dough","steps":["3","4","5"]},{"id":"baking-finishing","name":"Scoring, Baking & Finishing","description":"Score, bake and finish with aromatic oil","order":3,"component_id":"finishing","steps":["6","7","8"]}]'::jsonb,
    '["Preheat deck oven to 260°C","Prepare chiller tray with rack for brushing aromatic oil","Prepare aromatic olive oil mixture by mixing olive oil with crushed garlic, oregano, and rosemary."]'::jsonb,
    135,
    4,
    2,
    user_id,
    'published',
    'f1a2b3c4-d5e6-7f8a-9b0c-1d2e3f4a5b6c-thumbnail.png'
  ),
  (
    'a1b2c3d4-e5f6-7a8b-9c0d-1e2f3a4b5c6d',
    'Granola Cookies',
    'Biscuit Granola',
    'fr',
    'Chewy cookies packed with dried fruits and rolled oats, combining the wholesome flavors of granola in a delicious cookie form',
    'sweets',
    'cookies',
    '[{"id":"main","name":"Main","description":"Primary cookie ingredients with dried fruits and oats","order":1,"ingredients":[{"name":"Butter","amount":"85","unit":"g","is_flour":false},{"name":"Brown sugar","amount":"85","unit":"g","is_flour":false},{"name":"Sugar","amount":"86","unit":"g","is_flour":false},{"name":"Salt","amount":"2","unit":"g","is_flour":false},{"name":"Egg","amount":"37","unit":"g","is_flour":false},{"name":"Flour T55 Classique","amount":"152","unit":"g","is_flour":true},{"name":"Baking soda","amount":"1","unit":"g","is_flour":false},{"name":"Baking powder","amount":"2","unit":"g","is_flour":false},{"name":"Dried apricot","amount":"70","unit":"g","is_flour":false},{"name":"Dried cranberry","amount":"70","unit":"g","is_flour":false},{"name":"Rolled oat","amount":"33","unit":"g","is_flour":false}]}]'::jsonb,
    '[{"step":"1","content":"Crémage Part 1: Mix butter, brown sugar and white sugar until light and fluffy, about 3-5 minutes on medium speed.","remark":"Butter should be at room temperature for proper creaming. The mixture should become noticeably lighter in color and increased in volume."},{"step":"2","content":"Crémage Part 2: Add egg gradually, beating well after addition until fully incorporated.","remark":"Adding egg too quickly can cause the mixture to curdle. Mix until smooth before proceeding."},{"step":"3","content":"Crémage Part 3: In a separate bowl, whisk together flour, baking soda, baking powder, and salt."},{"step":"4","content":"Crémage Part 4: Add the dry ingredients to the creamed mixture and mix on low speed until just combined."},{"step":"5","content":"Mix in dried apricots, dried cranberries, and rolled oats until evenly distributed throughout the dough."},{"step":"6","content":"Optional: Chill the dough in refrigerator for 30 minutes to 1 hour for easier handling.","remark":"Chilling helps prevent spreading during baking and makes shaping easier."},{"step":"7","content":"Shaping: Divide dough into 20 pieces of 30g each. Roll into balls and flatten slightly on a baking sheet."},{"step":"8","content":"Apply egg wash to the tops of the cookies for a golden finish."},{"step":"9","content":"Bake in convection oven at 170°C for 9 - 10 minutes until edges are lightly golden."},{"step":"10","content":"Let cool on baking sheet for 5 minutes before transferring to a wire rack."}]'::jsonb,
    NULL,
    '["Preheat convection oven to 170°C"]'::jsonb,
    45,
    20,
    1,
    user_id,
    'published',
    'a1b2c3d4-e5f6-7a8b-9c0d-1e2f3a4b5c6d-thumbnail.png'
  ),
  (
    'b2c3d4e5-f6a7-8b9c-0d1e-2f3a4b5c6d7e',
    'Cheese Bread',
    'Pain au Fromage',
    'fr',
    'Savory French cheese bread enriched with grated Parmesan cheese, shaped into bâtards with a golden crust and soft, cheesy interior',
    'breads',
    'enriched-dough',
    '[{"id":"main-dough","name":"Main Dough","description":"Primary bread ingredients with Parmesan cheese","order":1,"ingredients":[{"name":"Flour T55 Classique","amount":"362","unit":"g","is_flour":true},{"name":"Water","amount":"205","unit":"g","is_flour":false},{"name":"Milk","amount":"36","unit":"g","is_flour":false},{"name":"Egg","amount":"18","unit":"g","is_flour":false},{"name":"Salt","amount":"6","unit":"g","is_flour":false},{"name":"Yeast","amount":"6","unit":"g","is_flour":false},{"name":"Sugar","amount":"7","unit":"g","is_flour":false},{"name":"Butter","amount":"11","unit":"g","is_flour":false},{"name":"Parmesan, grated","amount":"72","unit":"g","is_flour":false}]},{"id":"topping","name":"Topping","description":"Sea salt for finishing","order":2,"ingredients":[{"name":"Sea salt","amount":"SQ","unit":"","is_flour":false}]}]'::jsonb,
    '[{"step":"1","content":"(PI mixing) Mix all ingredients except Parmesan cheese on Low speed for 5 minutes, then continue on High speed for 8 minutes. Target dough temperature: 24°C - 26°C. Add the grated Parmesan cheese by hand and mix gently until evenly distributed.","remark":"Adding cheese by hand prevents breaking down of the cheese."},{"step":"2","content":"1st proofing: Bulk ferment for 30 - 40 minutes at room temperature."},{"step":"3","content":"Divide the dough into 6 pieces of 119g each."},{"step":"4","content":"Preshaping: Shape each piece into a loose ball. Let rest for 10 - 15 minutes."},{"step":"5","content":"Shaping: Shape each piece into a bâtard. Transfer to metal baguette tray."},{"step":"6","content":"Apply egg wash and score with saucisson cuts (parallel diagonal cuts) before proofing.","remark":"Scoring before proofing allows the cuts to open properly during the final rise."},{"step":"7","content":"2nd proofing: Proof for 30 - 40 minutes at 28°C with 80% humidity."},{"step":"8","content":"Optional: Sprinkle sea salt on top of the proofed loaves just before baking.","remark":"The sea salt adds flavor and creates an attractive finish on the crust."},{"step":"9","content":"Bake in deck oven at 200°C for 20 - 25 minutes, or convection oven at 170°C for 15 minutes until golden brown.","remark":"Use metal baguette trays for even heat distribution. Cheese may cause extra browning, so monitor closely. Deck oven heat distribution setting: (Top 80%/ Front 60%/ Bottom 10% or 0% if needed)"}]'::jsonb,
    '[{"id":"dough-preparation","name":"Dough Preparation & First Proof","description":"Mix the dough and first proofing","order":1,"component_id":"main-dough","steps":["1","2"]},{"id":"shaping-proofing","name":"Scaling, Shaping & Second Proof","description":"Scale, shape and final proofing","order":2,"component_id":"main-dough","steps":["3","4","5","6","7"]},{"id":"baking-finishing","name":"Scoring, Baking & Finishing","description":"Score, bake with sea salt topping","order":3,"component_id":"topping","steps":["8","9"]}]'::jsonb,
    '["Preheat deck oven to 200°C or convection oven to 170°C","Prepare metal baguette tray"]'::jsonb,
    95,
    6,
    2,
    user_id,
    'published',
    'b2c3d4e5-f6a7-8b9c-0d1e-2f3a4b5c6d7e-thumbnail.png'
  ),
  (
    'a1b2c3d4-e5f6-7890-abcd-ef1234567890',
    'Cereal Sandwich Bread',
    'Pain de Mie aux Céréales',
    'fr',
    'Cereals sandwich bread with mixed seeds and oats, perfect for sandwiches',
    'breads',
    'enriched-dough',
    '[{"id":"main","name":"Main Dough","description":"Primary bread ingredients","order":1,"ingredients":[{"name":"Flour T55 Classique","amount":"246","unit":"g","is_flour":true},{"name":"Water","amount":"151","unit":"g","is_flour":false},{"name":"Salt","amount":"6","unit":"g","is_flour":false},{"name":"Yeast","amount":"5","unit":"g","is_flour":false},{"name":"Sugar","amount":"15","unit":"g","is_flour":false},{"name":"Milk powder","amount":"10","unit":"g","is_flour":false},{"name":"Butter","amount":"18","unit":"g","is_flour":false}]},{"id":"seeds","name":"Mixed Seed (Soaked Overnight)","description":"Seeds that need to be soaked overnight","order":2,"ingredients":[{"name":"White sesame, toasted","amount":"15","unit":"g","is_flour":false},{"name":"Sunflower seed, toasted","amount":"15","unit":"g","is_flour":false},{"name":"Flax seeds, toasted","amount":"15","unit":"g","is_flour":false},{"name":"Water","amount":"49","unit":"g","is_flour":false},{"name":"Rolled oat (not soaked)","amount":"15","unit":"g","is_flour":false}]},{"id":"topping","name":"Topping","description":"For finishing the bread","order":3,"ingredients":[{"name":"Rolled oat","amount":"as needed","unit":"","is_flour":false},{"name":"Egg wash","amount":"as needed","unit":"","is_flour":false}]}]'::jsonb,
    '[{"step":"1","content":"(PI mixing) Mix all ingredients on Low speed for 5 minutes, and continue on High speed for 8 minutes. Target dough temperature: 24 to 26°C.","remark":"PI (Pétrissage Intensifié - Intensive Kneading) method uses extended high-speed mixing for maximum gluten development in enriched doughs. The longer high-speed phase creates strong gluten networks essential for soft, fine-textured breads."},{"step":"2","content":"Mix in the soaked mixed seeds and rolled oats into the dough until well combined."},{"step":"3","content":"1st proofing: 30 - 40 minutes at 25°C."},{"step":"4","content":"Divide the dough into 2 pieces of 275g each."},{"step":"5","content":"Shape into bâtard and place in bread mold (10cm x 22cm x 9cm, WxLxH)."},{"step":"6","content":"Brush the top of the bâtard with egg wash. Then, roll the egg-washed area in a tray of rolled oats."},{"step":"7","content":"2nd proofing: 60 - 70 minutes at 28°C, 80% humidity."},{"step":"8","content":"Bake in convection oven at 150°C (fan speed #2), for 15 minutes, then increase to 165°C (fan speed #3) for 8 minutes."}]'::jsonb,
    NULL,
    '["Soak white sesame seeds, sunflower seeds and flax seeds overnight in water","Preheat oven to 150°C"]'::jsonb,
    180,
    2,
    2,
    user_id,
    'published',
    'a1b2c3d4-e5f6-7890-abcd-ef1234567890-thumbnail.png'
  ),
  (
    'c5d6e7f8-9a0b-1c2d-3e4f-567890abcdef',
    'Tabatiere Bread',
    'Pain Tabatière',
    'fr',
    'The name "tabatière" (snuffbox) comes from its distinctive shape. It''s essentially a round or oval loaf with an indentation or "lid" that resembles an old-fashioned snuffbox.',
    'breads',
    'lean-dough',
    '[{"id":"main","name":"Main","description":"Primary bread ingredients","order":1,"ingredients":[{"name":"Flour T55 Classique","amount":"840","unit":"g","is_flour":true},{"name":"Water","amount":"554","unit":"g","is_flour":false},{"name":"Yeast","amount":"11","unit":"g","is_flour":false},{"name":"Salt","amount":"17","unit":"g","is_flour":false}]},{"id":"finishing","name":"Finishing","description":"Finishing","order":1,"ingredients":[{"name":"Olive oil","amount":"SQ","unit":"","is_flour":false}]}]'::jsonb,
    '[{"step":"1","content":"Mix flour and water on Low speed for 5 minutes."},{"step":"2","content":"Add salt and yeast. Let rest for 10 minutes (autolyse)."},{"step":"3","content":"(PA mixing) Mix on Low speed for 5 minutes, and continue on High speed for 5 minutes.","remark":"PA (Pétrissage Amélioré - Improved Kneading) method provides moderate gluten development ideal for lean doughs like baguettes. The shorter high-speed phase prevents overheating while achieving proper dough structure."},{"step":"2","content":"1st proofing: 30 - 40 minutes at 25°C."},{"step":"3","content":"Divide the dough into 4 pieces of 350g each."},{"step":"4","content":"Shape each piece into a loose ball. Let rest for 10 - 15 minutes."},{"step":"5","content":"Shape into Tabatière: With the seam side on the table surface, use a rolling pin to roll out the top 30% of the ball outwards into a flat surface. Continue rolling until the size of this flat area is about the size of of the un-rolled ball. Spread olive oil using a brush onto the perimeter of this flat area, except the area shared with the ball. Lift this flap up and cover the ball."},{"step":"6","content":"Flip the Tabatière upside-down (the seam should be facing up towards you), and transfer to a floured couche or towel."},{"step":"7","content":"2nd proofing: 60 - 70 minutes at 25°C, 70% humidity. Once the proofing is complete, flip it upside-down so that the seam faces down."},{"step":"8","content":"Optional: Score with leaf cut pattern before baking."},{"step":"9","content":"Bake in deck oven at 240°C for 24 minutes."}]'::jsonb,
    NULL,
    '["Preheat deck oven to 240°C"]'::jsonb,
    120,
    4,
    3,
    user_id,
    'published',
    'c5d6e7f8-9a0b-1c2d-3e4f-567890abcdef-thumbnail.png'
  ),
  (
    'e9f0a1b2-c3d4-5e6f-7890-123456789abc',
    'Almond Croissant',
    'Croissant aux Amandes',
    'fr',
    'Classic French almond croissant with buttery laminated dough, almond cream filling, and toasted almond topping',
    'breads',
    'enriched-dough',
    '[{"id":"dough","name":"Dough","description":"","order":1,"ingredients":[{"name":"Flour T45 Gruau","amount":"300","unit":"g","is_flour":true},{"name":"Flour T55 Classique","amount":"300","unit":"g","is_flour":true},{"name":"Water","amount":"288","unit":"g","is_flour":false},{"name":"Yeast","amount":"27","unit":"g","is_flour":false},{"name":"Salt","amount":"13","unit":"g","is_flour":false},{"name":"Sugar","amount":"78","unit":"g","is_flour":false},{"name":"Milk powder","amount":"12","unit":"g","is_flour":false},{"name":"Dry butter","amount":"300","unit":"g","is_flour":false}]},{"id":"almond_cream","name":"Crème d''Amande","description":"Almond cream filling","order":2,"ingredients":[{"name":"Butter","amount":"200","unit":"g","is_flour":false},{"name":"Icing sugar","amount":"200","unit":"g","is_flour":false},{"name":"Egg","amount":"120","unit":"g","is_flour":false},{"name":"Rum","amount":"16","unit":"g","is_flour":false},{"name":"Almond extract","amount":"as needed","unit":"","is_flour":false},{"name":"Flour T55 Classique","amount":"20","unit":"g","is_flour":false},{"name":"Almond powder","amount":"200","unit":"g","is_flour":false}]},{"id":"syrup","name":"Sugar Syrup","description":"For brushing croissants","order":3,"ingredients":[{"name":"Water","amount":"1000","unit":"g","is_flour":false},{"name":"Sugar","amount":"500","unit":"g","is_flour":false}]},{"id":"finishing","name":"Finishing","description":"Toppings and glaze","order":4,"ingredients":[{"name":"Sliced almonds","amount":"as needed","unit":"","is_flour":false},{"name":"Blond glaze","amount":"400","unit":"g","is_flour":false},{"name":"Icing sugar","amount":"as needed","unit":"","is_flour":false},{"name":"Egg wash","amount":"as needed","unit":"","is_flour":false}]}]'::jsonb,
    '[{"step":"1","content":"(PVL mixing) Mix all main dough ingredients except dry butter on Low speed for 8 minutes, then continue on High speed for 3 minutes. Target dough temperature: 24°C - 26°C.","remark":"PVL (Pétrissage à Vitesse Lente) method ensures proper gluten development without overheating the dough. Monitor dough temperature carefully as enriched doughs can warm quickly."},{"step":"2","content":"1st proofing: Bulk ferment for 15 - 25 minutes at 25°C."},{"step":"3","content":"Flatten the dough into a 20x30cm rectangle. You may want to fold a baking sheet into the 20x30cm rectangle as a guideline. Freeze for around 15 minutes.","remark":"Freezing helps firm the dough for easier lamination and prevents the butter from melting during the folding process."},{"step":"4","content":"Shape dry butter to 20x15 cm with a baking sheet and rolling pin. Re-refrigerate if needed, or you can use it immediately if it''s still hard. Place the dry butter rectangle in the middle of the rectangle dough. Cut the sides and place them on top of the butter to form the top layer, stretching the dough if needed to join the seams."},{"step":"5","content":"Perform lamination: Roll the dough to 7mm, perform a double fold. Then, the roll the dough to 7mm again, followed by one single fold."},{"step":"6","content":"Freeze for minimum 25 minutes."},{"step":"7","content":"Roll out the dough thickness of 3mm, with a height of 28cm (the width can be any cm). Along the length of the dough, mark out the 4.5cm, 13.5cm, 22.5cm, ... on the top of the dough. Then, mark out the 9cm, 18cm, 27cm, ... on the bottom of the dough. Using these marks as guidelines, cut out triangles, each of base 9cm and height 30cm.","remark":""},{"step":"8","content":"Roll each triangle from the wide base toward the point, stretching slightly to achieve the classic crescent shape. Place seam-side down on baking sheets.","remark":"Make sure to press down the tip of the triangle into the bottom of the croissant and make it flat. Otherwise the croissant will be tilted to one side and cause uneven proofing and subsequently, an unevenly-shaped croissant."},{"step":"9","content":"2nd proofing: Proof for 90 - 130 minutes at 28°C with 80% humidity."},{"step":"10","content":"Apply egg wash and bake in convection oven at 165°C for 16 minutes until golden brown. Cool completely and store croissants in chiller overnight for assembly.","remark":"Day-old croissants work better for almond croissants as they hold their shape when cut and absorb the syrup without becoming soggy."},{"step":"11","content":"Make almond cream (Crémage method): Cream the butter and icing sugar until light and fluffy. Gradually add eggs, beating well after each addition. Mix in rum and almond extract, then fold in flour and almond powder until just combined. Keep at room temperature for easy spreading.","remark":"Crémage creates a light, airy texture. The cream should be smooth and pipeable - if too stiff, beat briefly to restore spreadability."},{"step":"12","content":"Make sugar syrup: Bring water and sugar to a rolling boil, stirring until sugar dissolves completely. Cool down completely and store in chiller.","remark":"The syrup should be completely cool before use to prevent melting the almond cream during assembly."},{"step":"13","content":"Assembly preparation: Using a sharp serrated knife, carefully slice each day-old croissant at a slight angle (10° from horizontal) in half. Brush the insides of the croissant generously with the cooled sugar syrup.","remark":"The syrup adds moisture and sweetness while helping the almond cream adhere to the croissant layers."},{"step":"14","content":"Spread a generous layer of almond cream on the bottom half of each croissant using an offset spatula or piping bag, then sandwich with the top half.","remark":"The filling should be visible at the edges but not overflowing."},{"step":"15","content":"Using a piping bag, spread almond cream in a single line along the length of the top of the assembled croissant, and sprinkle evenly with sliced almonds, pressing gently to adhere.","remark":"The top layer of almond cream will create a golden, slightly caramelized surface during baking. Sliced almonds add texture and visual appeal."},{"step":"16","content":"Final baking: Bake in convection oven at 150°C for 20 minutes, or in deck oven at 200°C for 20 - 25 minutes with heat distribution Top 60%/ Front 60%/ Bottom 10% using wire rack.","remark":"The almond cream should be golden brown and set, and the croissants should be heated through. Wire rack allows air circulation for even heating."},{"step":"17","content":"Finishing: While still warm, brush with blond pastry glaze for a glossy finish, or alternatively, dust with icing sugar once completely cooled for a classic presentation.","remark":"Blond glaze (diluted apricot jam) provides professional shine and helps preserve moisture. Icing sugar offers traditional French bakery appearance but should only be applied when cool to prevent melting."}]'::jsonb,
    '[{"id":"dough-preparation","name":"Croissant Dough Preparation","description":"Prepare the laminated croissant dough","order":1,"component_id":"dough","steps":["1","2","3","4","5","6","7","8","9","10"]},{"id":"almond-cream-preparation","name":"Almond Cream Preparation","description":"Prepare the crème d''amande filling","order":2,"component_id":"almond_cream","steps":["11"]},{"id":"syrup-preparation","name":"Sugar Syrup Preparation","description":"Prepare the brushing syrup","order":3,"component_id":"syrup","steps":["12"]},{"id":"assembly-finishing","name":"Assembly & Finishing","description":"Assemble almond croissants and final baking","order":4,"component_id":"finishing","steps":["13","14","15","16","17"]}]'::jsonb,
    '["Chill the dry butter in the refrigerator until lamination","Prepare croissants the day before and chill overnight","Preheat convection oven to 165°C for initial baking, then 150°C for final assembly"]'::jsonb,
    1440,
    12,
    5,
    user_id,
    'published',
    'e9f0a1b2-c3d4-5e6f-7890-123456789abc-thumbnail.png'
  ),
  (
    '785502b9-579a-49ff-b688-a0b054db3972',
    'Danish Torsade Praliné',
    NULL,
    NULL,
    'Danish twisted pastry filled with chocolate chips and praliné pastry cream',
    'breads',
    'enriched-dough',
    '[{"id":"dough","name":"Dough","description":"Main pastry dough","order":1,"ingredients":[{"name":"Flour T45 Gruau","amount":"256","unit":"g","is_flour":true},{"name":"Flour T55 Classique","amount":"256","unit":"g","is_flour":true},{"name":"Milk","amount":"189","unit":"g","is_flour":false},{"name":"Egg","amount":"82","unit":"g","is_flour":false},{"name":"Salt","amount":"10","unit":"g","is_flour":false},{"name":"Yeast","amount":"20","unit":"g","is_flour":false},{"name":"Sugar","amount":"51","unit":"g","is_flour":false},{"name":"Butter","amount":"20","unit":"g","is_flour":false}]},{"id":"lamination","name":"Lamination","description":"Dry butter for lamination","order":2,"ingredients":[{"name":"Dry butter","amount":"256","unit":"g","is_flour":false}]},{"id":"pastry-cream","name":"Praliné Pastry Cream","description":"Crème Pâtissière Praliné for filling","order":3,"ingredients":[{"name":"Milk","amount":"154","unit":"g","is_flour":false},{"name":"Sugar (1)","amount":"15","unit":"g","is_flour":false},{"name":"Sugar (2)","amount":"15","unit":"g","is_flour":false},{"name":"Egg yolk","amount":"31","unit":"g","is_flour":false},{"name":"Flour T55 Classique","amount":"8","unit":"g","is_flour":false},{"name":"Cornstarch","amount":"8","unit":"g","is_flour":false},{"name":"Butter","amount":"15","unit":"g","is_flour":false},{"name":"Hazelnut Praliné","amount":"23","unit":"g","is_flour":false}]},{"id":"filling","name":"Assembly Filling","description":"Final filling components","order":4,"ingredients":[{"name":"Chocolate chip","amount":"100","unit":"g","is_flour":false}]}]'::jsonb,
    '[{"step":"1","content":"(PVL mixing) Mix on Low speed for 8 minutes, and continue on High speed for 4 minutes. Target dough temperature: 24 - 26°C.","remark":"PVL (Pétrissage en Vitesse Lente) is slow-speed mixing that develops gluten gently for enriched doughs."},{"step":"2","content":"1st proofing: 15 - 25 minutes at 25°C."},{"step":"3","content":"Heat milk with Sugar (1) in a saucepan until just simmering.","remark":"Heat gently to avoid scorching. The milk should be steaming but not vigorously boiling."},{"step":"4","content":"In a separate bowl, whisk egg yolks with Sugar (2) until pale. Add flour and cornstarch, whisking until smooth.","remark":"Ensure no lumps remain in the egg mixture. The mixture should be pale yellow and smooth."},{"step":"5","content":"Temper the egg mixture by slowly adding the hot milk while whisking continuously to prevent curdling."},{"step":"6","content":"Return the mixture to the saucepan and cook over medium heat, whisking constantly, until thickened to a smooth, silky consistency.","remark":"The pastry cream is ready when it coats the back of a spoon and holds its shape when whisked."},{"step":"7","content":"Remove from heat immediately and whisk in butter and hazelnut praliné until fully incorporated.","remark":"Adding butter and praliné while hot ensures smooth incorporation and prevents graininess."},{"step":"8","content":"Cover with plastic wrap pressed directly onto the surface to prevent skin formation. Refrigerate until needed.","remark":"Direct contact with plastic wrap prevents oxidation and skin formation. Can be stored for up to 3 days at 4°C."},{"step":"9","content":"Flatten dough to 20x30 cm rectangle."},{"step":"10","content":"Freeze for about 15-20 minutes to firm up the dough."},{"step":"11","content":"Shape dry butter to 20x15 cm with a baking sheet and rolling pin. Re-refrigerate if needed, or you can use it immediately if it''s still hard. Place the dry butter rectangle in the middle of the rectangle dough. Cut the sides and place them on top of the butter to form the top layer, stretching the dough if needed to join the seams."},{"step":"12","content":"Perform lamination: Roll the dough to 7mm, perform a double fold. Then, the roll the dough to 7mm again, followed by one single fold.","remark":"Lamination creates the flaky layers characteristic of Danish pastry."},{"step":"13","content":"Freeze for minimum 25 minutes."},{"step":"14","content":"Roll out the dough to 40x45 cm at 3mm thickness. Trim off any uneven edges so you have a clean rectangle. Along the 40 cm side (the short side), measure up 5cm from the bottom edge. Lightly mark this line across. Brush this 5cm bottom strip with water — this will help seal the roll later. From the top edge, fold the dough down exactly halfway to the 5cm mark; this crease will be at 17.5 cm from the top (which is the middle of the 35 cm length, after subtracting the 5cm area). Unfold it—this line marks the halfway point."},{"step":"15","content":"Bring the praliné pastry cream out of the refrigerator and whisk vigorously to smooth it out and return it to a pipeable consistency. Spread the pastry cream evenly over the bottom area (below the 17.5cm mark), then sprinkle chocolate chips on top of the cream.","remark":"Cold pastry cream needs to be whisked to restore its smooth, spreadable texture before use."},{"step":"16","content":"Fold the top half of the dough to the bottom half (with cream and choc. chips). Fold up the 5cm bottom strip and seal the seam. Then, cut into 3 cm strips, then perform double twist to create torsade shape.","remark":"The double twist creates the characteristic spiral appearance of torsade pastries."},{"step":"17","content":"Optional: Place in baguette tray for uniform shape during proofing and baking."},{"step":"18","content":"2nd proofing: 60 - 70 minutes at 28°C with 80% humidity."},{"step":"19","content":"Apply egg wash before baking."},{"step":"20","content":"Bake in convection oven at 155°C for 18 - 20 minutes, or in deck oven at 180°C for 18 - 22 minutes with heat setting 40/40/10."}]'::jsonb,
    NULL,
    '["Preheat convection oven to 155°C, or deck oven to 180°C","Chill the dry butter in the refrigerator until lamination"]'::jsonb,
    300,
    15,
    4,
    user_id,
    'published',
    '785502b9-579a-49ff-b688-a0b054db3972-thumbnail.png'
  ),
  (
    '8c9d0e1f-2a3b-4c5d-6e7f-8a9b0c1d2e3f',
    'Chocolate Croissant',
    'Pain au Chocolat',
    'fr',
    'Buttery, flaky French viennoiserie filled with rich chocolate batons—crafted for a tender, airy crumb and irresistible melt-in-your-mouth layers.',
    'breads',
    'enriched-dough',
    '[{"id":"dough","name":"Main Dough","description":"Enriched laminated pastry dough using PVL method","order":1,"ingredients":[{"name":"T45 Gruau Flour","amount":"360","unit":"g","is_flour":true},{"name":"T55 Classique Flour","amount":"240","unit":"g","is_flour":true},{"name":"Water","amount":"288","unit":"g","is_flour":false},{"name":"Fresh yeast","amount":"27","unit":"g","is_flour":false},{"name":"Salt","amount":"13","unit":"g","is_flour":false},{"name":"Sugar","amount":"78","unit":"g","is_flour":false},{"name":"Milk powder","amount":"12","unit":"g","is_flour":false}]},{"id":"butter","name":"Lamination Butter","description":"Dry butter for laminating the dough","order":2,"ingredients":[{"name":"Dry butter","amount":"300","unit":"g","is_flour":false}]},{"id":"filling","name":"Chocolate Filling","description":"Chocolate baking sticks for filling","order":3,"ingredients":[{"name":"Chocolate baking sticks","amount":"24","unit":"pcs","is_flour":false}]},{"id":"finishing","name":"Finishing","description":"Egg wash for golden finish","order":4,"ingredients":[{"name":"Egg","amount":"SQ","unit":"","is_flour":false}]}]'::jsonb,
    '[{"step":"1","content":"(PVL mixing) Mix all dough ingredients. Target dough temperature: 24 - 26°C.","remark":"PVL (Pétrissage à Vitesse Lente - Slow Speed Kneading) method develops gluten gently, ideal for laminated doughs."},{"step":"2","content":"1st proofing: 15 - 25 minutes at room temperature of 25°C."},{"step":"3","content":"Flatten dough to 20x30 cm rectangle. Chill overnight in freezer or refrigerator.","remark":"Chilling firms the dough and makes lamination easier while preventing butter breakthrough."},{"step":"4","content":"Prepare dry butter block to 20x15 cm rectangle. Butter should be pliable but not soft."},{"step":"5","content":"Place dry butter rectangle in the middle of the 20x30cm dough. Cut the sides and place them on top of the butter to form the top layer, stretching the dough if needed to join the seams."},{"step":"6","content":"Perform lamination: Roll the dough to 7mm, perform a double fold. Rotate the dough 90°, then roll the dough to 7mm again, followed by one single fold.","remark":"Lamination creates the flaky layers characteristic of croissant."},{"step":"7","content":"Freeze for around 25 minutes between folds to maintain butter consistency."},{"step":"8","content":"Roll out dough to 42 x 50(+) cm (H x L), 3mm thickness. Trim the sides until you have a clean rectangle."},{"step":"9","content":"Divide the dough into equal top and bottom. You could do that by folding down the top edge of the dough to the bottom edge, then unfold it to make a mark. Along the length (50cm+), mark at 7cm intervals. Then, cut the dough into rectangles of 7cm x 15-21 cm."},{"step":"10","content":"Shape into chocolate croissants by placing a chocolate stick and folding the dough over it. Press down to secure the chocolate stick. Then, place a 2nd chocolate stick on top of the newly created seam. Finally, roll the dough until the seam is sealed.","remark":"You can also place 1 chocolate stick at each end of the rectangle, then roll towards the center."},{"step":"11","content":"2nd proofing: 1h 30mins - 2h 10mins at 28°C with 80% humidity on baking tray."},{"step":"12","content":"Apply egg wash evenly across surface for golden color."},{"step":"13","content":"Bake in convection oven at 165°C for 16 minutes until golden brown."},{"step":"14","content":"Let cool for 10 minutes before serving."}]'::jsonb,
    '[{"id":"dough-prep","name":"Dough Preparation","description":"Mix and develop the enriched dough using PVL method","order":1,"component_id":"dough","steps":["1","2","3"]},{"id":"lamination","name":"Lamination Process","description":"Incorporate butter and create layers through folding","order":2,"component_id":"butter","steps":["4","5","6","7"]},{"id":"shaping-baking","name":"Shaping & Baking","description":"Shape pastries and bake to perfection","order":3,"component_id":"filling","steps":["8","9","10","11","12","13","14"]}]'::jsonb,
    '["Preheat convection oven to 165°C.","Refrigerate dry butter until lamination."]'::jsonb,
    360,
    24,
    3,
    user_id,
    'published',
    '8c9d0e1f-2a3b-4c5d-6e7f-8a9b0c1d2e3f-thumbnail.png'
  ),
  (
    '9d0e1f2a-3b4c-5d6e-7f8a-9b0c1d2e3f4a',
    'Focaccia Provençale',
    'Provence Focaccia',
    'en',
    'Traditional Italian flatbread with Provençal toppings including Kalamata olives, sun-dried tomatoes, and herbs',
    'breads',
    'enriched-dough',
    '[{"id":"main-dough","name":"Main Dough","description":"Base focaccia dough with potato flakes and milk powder","order":1,"ingredients":[{"name":"T55 Tradition Flour","amount":"270","unit":"g","is_flour":true},{"name":"Water","amount":"180","unit":"g","is_flour":false},{"name":"Fresh yeast","amount":"3","unit":"g","is_flour":false},{"name":"Salt","amount":"5","unit":"g","is_flour":false},{"name":"Potato flakes","amount":"11","unit":"g","is_flour":false},{"name":"Milk powder","amount":"8","unit":"g","is_flour":false}]},{"id":"fermented-dough","name":"Fermented Dough","description":"Pre-fermented dough for enhanced flavor","order":2,"ingredients":[{"name":"Fermented dough","amount":"54","unit":"g","is_flour":false}]},{"id":"bassinage","name":"Bassinage Oil","description":"Olive oil added during final mixing stage","order":3,"ingredients":[{"name":"Extra virgin olive oil","amount":"22","unit":"g","is_flour":false}]},{"id":"inclusions","name":"Mediterranean Inclusions","description":"Chopped olives, tomatoes, and herbs mixed into dough","order":4,"ingredients":[{"name":"Kalamata olives, chopped","amount":"54","unit":"g","is_flour":false},{"name":"Sun-dried tomatoes, chopped","amount":"54","unit":"g","is_flour":false},{"name":"Provence herbs","amount":"2","unit":"g","is_flour":false}]},{"id":"toppings","name":"Fresh Toppings","description":"Fresh ingredients for decorating before baking","order":5,"ingredients":[{"name":"Cherry tomatoes, halved","amount":"12","unit":"pcs","is_flour":false},{"name":"Polenta flour","amount":"SQ","unit":"","is_flour":false},{"name":"Whole Kalamata olives","amount":"6","unit":"pcs","is_flour":false},{"name":"Whole green olives","amount":"6","unit":"pcs","is_flour":false},{"name":"Fresh rosemary","amount":"SQ","unit":"","is_flour":false}]},{"id":"finishing","name":"Finishing","description":"Final brushing and seasoning after baking","order":6,"ingredients":[{"name":"Olive oil","amount":"SQ","unit":"","is_flour":false},{"name":"Provence herbs","amount":"SQ","unit":"","is_flour":false},{"name":"Sea salt flakes","amount":"SQ","unit":"","is_flour":false}]}]'::jsonb,
    '[{"step":"1","content":"(PI mixing) Mix flour, water, yeast, salt, potato flakes, and milk powder on Low speed for 5 minutes. Continue on High speed for 2 minutes. Add fermented dough and mix on High speed for 8 - 10 minutes. Target dough temperature: 24 - 26°C.","remark":"PI (Pétrissage Intensifié - Intensive Kneading) develops strong gluten structure ideal for focaccia''s open crumb."},{"step":"2","content":"Add bassinage olive oil gradually during the last 3 minutes of High speed mixing. Then add chopped olives, sun-dried tomatoes, and Provence herbs on Low speed until just incorporated.","remark":"Bassinage technique adds oil gradually to improve dough extensibility without breaking gluten structure."},{"step":"3","content":"1st proofing: 30 - 60 minutes at room temperature."},{"step":"4","content":"Cut the dough into 2 equal pieces. Pre-shape into loose balls."},{"step":"5","content":"Sprinkle polenta flour on baking paper. Flatten each round into a ring shape with 16 cm in diameter.","remark":"Polenta prevents sticking and adds texture to the bottom crust."},{"step":"6","content":"2nd proofing: 1hr 30mins - 2h at 29°C with 80% humidity."},{"step":"7","content":"Create dimples with fingertips across the surface, coating your fingers with water to prevent sticking.","remark":"Dimpling creates the characteristic focaccia texture and holds toppings."},{"step":"8","content":"Add green olives, Kalamata olives, and cherry tomatoes. Then, sprinkle with polenta flour and fresh rosemary."},{"step":"9","content":"Place the focaccia rings on top of a rack, and place the rack on top of a baking tray. Transfer and bake in deck oven at 240°C (with steam) for 13 - 16 minutes."},{"step":"10","content":"Remove rings and continue baking for 2 - 3 minutes to crisp the sides."},{"step":"11","content":"Immediately brush with olive oil and sprinkle with Provence herbs and sea salt flakes."},{"step":"12","content":"Let cool for 10 minutes before serving."}]'::jsonb,
    '[{"id":"dough-mixing","name":"Dough Mixing & First Proof","description":"Mix dough using PI method with bassinage technique","order":1,"component_id":"main-dough","steps":["1","2","3"]},{"id":"shaping-proofing","name":"Shaping & Second Proof","description":"Scale, shape, and proof the focaccia rings","order":2,"component_id":"toppings","steps":["4","5","6","7"]},{"id":"topping-baking","name":"Topping & Baking","description":"Add toppings and bake with steam","order":3,"component_id":"finishing","steps":["8","9","10","11","12"]}]'::jsonb,
    '["Preheat deck oven to 240°C with steam capability","Prepare fermented dough in advance"]'::jsonb,
    240,
    2,
    2,
    user_id,
    'published',
    '9d0e1f2a-3b4c-5d6e-7f8a-9b0c1d2e3f4a-thumbnail.png'
  ),
  (
    '7a8b9c0d-1e2f-3a4b-5c6d-7e8f9a0b1c2d',
    'Quiche Lorraine',
    NULL,
    NULL,
    'Classic French savory tart with smoked bacon and Emmental cheese in a rich custard filling',
    'breads',
    'enriched-dough',
    '[{"id":"pastry","name":"Pâte à Foncer","description":"Traditional French pastry shell using sablage method","order":1,"ingredients":[{"name":"T55 Tradition Flour","amount":"336","unit":"g","is_flour":true},{"name":"Butter","amount":"168","unit":"g","is_flour":false},{"name":"Salt","amount":"5.5","unit":"g","is_flour":false},{"name":"Water","amount":"45","unit":"g","is_flour":false},{"name":"Eggs","amount":"56","unit":"g","is_flour":false}]},{"id":"filling","name":"Custard Filling","description":"Rich egg custard with bacon and cheese","order":2,"ingredients":[{"name":"Egg yolks","amount":"61","unit":"g","is_flour":false},{"name":"Whole eggs","amount":"122","unit":"g","is_flour":false},{"name":"Milk","amount":"183","unit":"g","is_flour":false},{"name":"Cream","amount":"183","unit":"g","is_flour":false},{"name":"Smoked bacon","amount":"122","unit":"g","is_flour":false},{"name":"Emmental cheese, grated","amount":"81","unit":"g","is_flour":false},{"name":"Salt","amount":"2","unit":"g","is_flour":false},{"name":"Nutmeg powder","amount":"SQ","unit":"","is_flour":false},{"name":"Black pepper","amount":"SQ","unit":"","is_flour":false}]}]'::jsonb,
    '[{"step":"1","content":"(Sablage method) Mix flour and butter until sandy texture. Add salt, then add water and eggs gradually.","remark":"Sablage creates a tender, crumbly pastry texture. Don''t overmix to avoid tough pastry."},{"step":"2","content":"Mix just until combined. Don''t over mix to avoid pastry shrinking during baking."},{"step":"3","content":"Divide dough into 305g pieces for individual quiches. Chill for minimum 30 minutes.","remark":"Chilling allows gluten to relax and prevents shrinkage."},{"step":"4","content":"Roll pastry to 2.5mm thickness. (Fonçage pâte brisée) Line a tart ring (20x2 cm, diameter x height) with the pastry dough, carefully pressing the dough into the corners and sides of the ring to create a base for the tart. Freeze before baking.","remark":"Freezing helps maintain shape during blind baking."},{"step":"5","content":"Blind bake with baking beans at 170°C for 15 - 20 minutes on oven rack. You may use plastic wrap to hold the baking beans in place over the pastry dough.","remark":"Blind baking, sometimes called pre-baking, is a process of baking a pie crust or other pastry without the filling. This is done to prevent the crust from becoming soggy from a wet filling."},{"step":"6","content":"Whisk together egg yolks, whole eggs, milk, and cream. Season with salt, nutmeg, and pepper.","remark":"Strain custard mixture if desired for silky smooth texture."},{"step":"7","content":"Fill pre-baked pastry shells with bacon, then pour custard filling over top. Add grated cheese on top of the custard filling."},{"step":"8","content":"Bake in convection oven at 160°C for 18 - 22 minutes until custard is set and some parts of the custard are browned."},{"step":"9","content":"Let cool for 10 minutes before serving."}]'::jsonb,
    '[{"id":"pastry-prep","name":"Pastry Preparation","description":"Prepare pâte brisée using sablage method","order":1,"component_id":"pastry","steps":["1","2","3","4"]},{"id":"blind-baking","name":"Blind Baking","description":"Pre-bake pastry shell with baking beans","order":2,"component_id":"pastry","steps":["5"]},{"id":"filling-final","name":"Filling & Final Baking","description":"Add filling and complete the quiche","order":3,"component_id":"filling","steps":["6","7","8"]}]'::jsonb,
    '["Preheat oven to 170°C for pastry blind baking"]'::jsonb,
    120,
    2,
    2,
    user_id,
    'published',
    '7a8b9c0d-1e2f-3a4b-5c6d-7e8f9a0b1c2d-thumbnail.png'
  );
END $$;

-- Commit the transaction
COMMIT;
